### ISSUE TITLE
please add google json on the app

### ISSUE THREAD

**Issue by mynameismhmd** [alper-efe-sahin/phone_number_sign_in#5]

**Comment by alperefesahin** [comment]
It's your responsibility because of every app has own configuration. Thanks!

**Comment by mynameismhmd** [comment]
it doesn't work with me that's why I need yours plz put it like others

**Comment by mynameismhmd** [comment]
I really need it please

**Comment by mynameismhmd** [comment]
fine ill take my job offer and go I really hate the GitHub programmers so much because they are always wrong

**Comment by alperefesahin** [comment]
dude, I can not give it to you because before I published this project I deleted it because of the SHA Keys. If you are an open source creator you should consider these things. Sorry about it, enjoy with the project. It's not hard to create a firebase app via Firebase.

**Comment by mynameismhmd** [comment]
ok than say goodbye to the job you could just add it rather than this nonsense
